theme: jekyll-theme-minimal
title: Seán P. Blake, PhD
description: Space Scientist/Geophysicist
logo: [https://user-images.githubusercontent.com/20742138/92676461-963e6b00-f2ef-11ea-8009-4361f41dbaef.jpg]
